(define (make-account balance password)
  (let ((wrong-password-count 0))
    (define (withdraw amount)
      (if (>= balance amount)
        (begin (set! balance (- balance amount))
               balance)
        "Insufficient funds"))
    (define (deposit amount)
      (set! balance (+ balance amount))
      balance)
    (define (call-the-cops)
      (newline)
      (display "Calling the cops")
      (newline))
    (define (dispatch p m)
      (define (wrong-password a)
        "Incorrect password")
      (define (check-password p)
        (cond ((eq? p password)
               (set! wrong-password-count 0)
               true)
              ((< wrong-password-count 7)
               (set! wrong-password-count
                 (+ wrong-password-count 1))
               false)
              (else
                (call-the-cops)
                false)))
      (if (check-password p)
        (cond ((eq? m 'withdraw) withdraw)
              ((eq? m 'deposit) deposit)
              (else (error "Unknown request -- MAKE-ACCOUNT" m)))
        wrong-password))
    dispatch))

(define acc (make-account 100 'secret-password))
((acc 'secret-password 'withdraw) 40)
((acc 'secret-password 'withdraw) 80)
((acc 'shit 'deposit) 50)
((acc 'shit 'deposit) 50)
((acc 'shit 'deposit) 50)
((acc 'shit 'deposit) 50)
((acc 'shit 'deposit) 50)
((acc 'shit 'deposit) 50)
((acc 'shit 'deposit) 50)
((acc 'shit 'deposit) 50)
((acc 'shit 'deposit) 50)
((acc 'secret-password 'deposit) 80)
((acc 'shit 'deposit) 50)
