((lambda (n)
   ((lambda (fact)
      (fact fact n))
    (lambda (ft k)
      (if (= k 1)
        1
        (* k (ft ft (- k 1)))))))
 10)
((lambda (n)
   ((lambda (fib)
      (fib fib n))
    (lambda (fibb k)
      (cond ((or (= k 0) (= k 1)) k)
            (else (+ (fibb fibb (- k 1))
                     (fibb fibb (- k 2))))))))
 10)

(define (f x)
  ((lambda (even? odd?)
     (even? even? odd? x))
   (lambda (ev? od? n)
     (if (= n 0) true (od? ev? od? (- n 1))))
   (lambda (ev? od? n)
     (if (= n 0) false (ev? ev? od? (- n 1))))))
(f 10)
(f 9)
